### ISSUE TITLE
Add api into Platform enumeration

### ISSUE THREAD

**Issue by shailendrabirthare** [snowplow/snowplow-dotnet-tracker#12]
We are planning to use Snowplow tracker for ASP.NET WEBAPI project. The ideal Platform value for us to use is 'api' but it is not present in current definition of enum. We are utilizing other Platform values for other digital products already.

**Comment by alexanderdean** [comment]
Hey @shailendrabirthare - "API" isn't the platform that your tracker is embedded in. I suspect your tracker is running on a server (`Srv`) platform? (If you need more granular data on your environment, you can use custom contexts.)

**Comment by shailendrabirthare** [comment]
Hi @alexanderdean,

Thanks for your prompt reply. 

I see your point. API project is a server side project and in fact we are using Platform.Srv. However, we are going to add .NET tracker in other server side code and we would like to distinguish between event tracked from api (api project) or srv (other server side project e.g. ASP.NET MVC or web form or Azure worker). Please see image that describe our setup.

I looked at the custom context and its not fit into our solution and feels like overkill. 

I feel the easier solution is to add api into Platform enum. A combination of appId and Platform gives us better segregation.

Let me know what you think.

![image](https://cloud.githubusercontent.com/assets/6496344/8719349/bcdd13fe-2bc8-11e5-9350-2eefb13591c1.png)

**Comment by alexanderdean** [comment]
I understand you would like to distinguish them but the platform is a physical/hardware platform, not a descriptor of what your app does. Over time [most everything](https://github.com/snowplow/snowplow/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Avro+support+%231%22) in atomic.events will move to custom contexts so it's worth making the leap.

**Comment by yalisassoon** [comment]
You could use the `app_id` field instead?

**Comment by shailendrabirthare** [comment]
@yalisassoon - Yes we can. Having appid separate our digital products and platform separate applications within a product, was the way we were originally planning to go (as shown in image above). However, I understand @alexanderdean point about Platform. We shall see another option (custom context - overkill or appId - Simple). Thanks guys.

**Comment by alexanderdean** [comment]
No problem, thanks @shailendrabirthare. BTW feel free to re-submit your PR with the removed imports if you like...
