### ISSUE TITLE
Add lock around AsyncEmitter.flush

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-dotnet-tracker#16]
See discussion in #14

**Comment by alexanderdean** [comment]
Not sure why Ed closed this, it will close on merge to master

**Comment by ninjabear** [comment]
hey @alexanderdean, I closed this because this commit is no longer in master - the code it references has been rewritten!

**Comment by alexanderdean** [comment]
Cool, thanks Ed, descheduling too.
