### ISSUE TITLE
Add support for dvce_sent_tstamp

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-dotnet-tracker#18]
This is related to: https://github.com/snowplow/snowplow/issues/2457

**Comment by bogaert** [comment]
@alexanderdean can we schedule this to the next release? - customer request.

**Comment by alexanderdean** [comment]
Scheduled!

**Comment by ninjabear** [comment]
Hey @jbeemster! Do you remember doing this? I think we may have missed it

**Comment by jbeemster** [comment]
I did do this yes - https://github.com/snowplow/snowplow-dotnet-tracker/blob/master/Snowplow.Tracker/Endpoints/SnowplowHttpCollectorEndpoint.cs#L284

and https://github.com/snowplow/snowplow-dotnet-tracker/blob/master/Snowplow.Tracker/Endpoints/SnowplowHttpCollectorEndpoint.cs#L156

**Comment by ninjabear** [comment]
ah nice! I've added this to the changelog, thanks @jbeemster !

**Comment by alexanderdean** [comment]
Okay, added ticket to add to CHANGELOG in future release
