### ISSUE TITLE
Add Windows Phone 8.x support

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-dotnet-tracker#4]
http://programmium.wordpress.com/2014/05/26/keen-io-windows-phone-8-1-and-nuget-package-creation/

**Comment by SeeD-Seifer** [comment]
Check https://github.com/snowplow/snowplow-dotnet-tracker/pull/10 for Portable support (including WinPhone 8)

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by paulboocock** [comment]
Going to give this tracker some love that it deserves. Closing this issue as no longer relevant.
