### ISSUE TITLE
Add missing dvce_sent_tstamp ticket to CHANGELOG

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-dotnet-tracker#66]
It's already been added to the release notes.

https://github.com/snowplow/snowplow-dotnet-tracker/issues/18

**Comment by ninjabear** [comment]
https://github.com/snowplow/snowplow-dotnet-tracker/blob/master/CHANGELOG#L38

^^ this has already been done @alexanderdean ?

**Comment by alexanderdean** [comment]
Ah! Cool, closing and de-scheduling
