### ISSUE TITLE
not able to Send/Track events

### ISSUE THREAD

**Issue by SagarPanwala** [snowplow/snowplow-dotnet-tracker#80]
Hi, 
I'm attaching my code of Xamarin.  Not able to send/track events. Count stays as 0
https://www.dropbox.com/s/zv4xxq9dmish2gz/SnowPlow.Demo.zip?dl=0

**Comment by BenFradet** [comment]
Hello @SagarPanwala, please raise your support requests on [our Discourse forum](https://discourse.snowplowanalytics.com/).
