### ISSUE TITLE
Stop disposing ConnectivityManager on Android

### ISSUE THREAD

**Issue by Amazia** [snowplow/snowplow-dotnet-tracker#82]
Hi,

On the Snowplow.Tracker.PlatformExtensions you use that lines of code:

```
using (var cm = (ConnectivityManager)Android.App.Application.Context.GetSystemService(Android.Content.Context.ConnectivityService))
{
    return cm.ActiveNetworkInfo;
}
```

But this code dispose the ConnectivityManager Service for the entire Application. I'm not sure that is the good practice.

In my application, it breaks my own Network Service helper because I keep a reference on the ConnectivityManager that you dispose.

My code : 

```
private ConnectivityManager _connectivityManager;

public NetworkStatusBroadcastReceiver()
{
    _connectivityManager = (ConnectivityManager)Application.Context.GetSystemService(Context.ConnectivityService);
}
```

After a call of your code, my _connectivityManager is disposed.

Regards

**Comment by alexanderdean** [comment]
Thanks for raising @Amazia
